### ISSUE TITLE
sphere_maker.ipynb is missing

### ISSUE THREAD

**Issue by Dan14** [nimlab/NHB_Taylor2023#1]
Thanks for sharing the code. would it be possible to add the sphere_maker.ipynb?

**Comment by Luna4257** [comment]
I am also looking forward to this code. 
Before it is uploaded, I used neurosynth to do this. Hope it can help you!

**Comment by clin045** [comment]
Apologies, notebook has now been added.

**Comment by Luna4257** [comment]
Thx!
